# FP-Growth Algorithm in Python

In [6]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

In [ ]:
data = [['Milk', 'Burgers', 'Buns', 'Ketchup'],
        ['Burgers', 'Buns', 'Ketchup', 'Coals'],
        ['Milk', 'Buns', 'Beer'],
        ['Burgers', 'Beer', 'Buns', 'Coals'],
        ['Milk', 'Ketchup'],
        ['Milk', 'Beer', 'Burgers', 'Buns', 'Ketchup', 'Coals'],
        ['Beer', 'Burgers', 'Buns', 'Ketchup', 'Coals'],
        ['Milk', 'Buns'],
        ['Burgers', 'Buns', 'Ketchup'],
        ['Beer', 'Burgers', 'Ketchup', 'Coals']]

In [28]:
# Encode data as market basket data
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)

df = pd.DataFrame(te_ary, columns=te.columns_)
df

    Beer   Buns  Burgers  Coals  Ketchup   Milk
0  False   True     True  False     True   True
1  False   True     True   True     True  False
2   True   True    False  False    False   True
3   True   True     True   True    False  False
4  False  False    False  False     True   True
5   True   True     True   True     True   True
6   True   True     True   True     True  False
7  False   True    False  False    False   True
8  False   True     True  False     True  False
9   True  False     True   True     True  False

In [27]:
fp = fpgrowth(df, min_support=0.25, use_colnames=True)

In [23]:
assoc = association_rules(fp, min_threshold=.5)
assoc[assoc['consequents'].apply(lambda x: 'Coals' in x)]

                  antecedents  ... zhangs_metric
15                  (Burgers)  ...      1.000000
18                  (Ketchup)  ...      0.416667
19                     (Buns)  ...      0.000000
22         (Burgers, Ketchup)  ...      0.625000
24                  (Burgers)  ...      1.000000
26                  (Ketchup)  ...      0.416667
27            (Buns, Burgers)  ...      0.625000
30                     (Buns)  ...      0.000000
31                  (Burgers)  ...      1.000000
34            (Buns, Ketchup)  ...      0.333333
38   (Buns, Burgers, Ketchup)  ...      0.333333
41            (Buns, Burgers)  ...      0.500000
43            (Buns, Ketchup)  ...      0.333333
45         (Burgers, Ketchup)  ...      0.500000
51                     (Beer)  ...      0.750000
60               (Buns, Beer)  ...      0.555556
63                     (Beer)  ...      0.666667
65      (Buns, Burgers, Beer)  ...      0.714286
68            (Buns, Burgers)  ...      0.500000
70               (Buns, Beer)  ...      0.555556
72            (Burgers, Beer)  ...      0.777778
75                     (Beer)  ...      0.666667
77            (Burgers, Beer)  ...      0.833333
79                  (Burgers)  ...      1.000000
81                     (Beer)  ...      0.750000
88            (Beer, Ketchup)  ...      0.714286
90                     (Beer)  ...      0.666667
93   (Burgers, Beer, Ketchup)  ...      0.714286
96         (Burgers, Ketchup)  ...      0.500000
97            (Burgers, Beer)  ...      0.777778
100           (Beer, Ketchup)  ...      0.714286
102                    (Beer)  ...      0.666667

[32 rows x 10 columns]